[package]
name = "sidequest"
version = "0.0.0"
authors = ["Sam Sartor <me@samsartor.com>"]

[dependencies]
sidequest_core = { path="core" }
failure = "0.1"
rayon = "^1.0.2"
gif = "0.10"

[workspace]
members = ["core"]
