[package]
name = "sidequest"
version = "0.0.0"
authors = ["Sam Sartor <me@samsartor.com>"]

[dependencies]
sidequest_core = { path="core" }
failure = "0.1"
rayon = "^1.0"
image = "0.19"
clap = "^2.32"
indicatif = "*"

[workspace]
members = ["core"]
