[package]
name = "sidequest_core"
version = "0.0.0"
authors = ["Sam Sartor <me@samsartor.com>"]

[dependencies]
num-traits = "0.2"
imgref = "^1.3"
ncollide = "0.14"
palette = "0.4"
rand = "0.5.5"

[dependencies.nalgebra]
version = "0.14"
features = ["serde-serialize"]
