[package]
name = "sidequest_core"
version = "0.0.0"
authors = ["Sam Sartor <me@samsartor.com>"]

[dependencies]
num-traits = "0.2"
serde = "^1.0"
serde_derive = "^1.0"
imgref = "^1.3"
ncollide = "0.14"
rayon = "^1.0.2"

[dependencies.nalgebra]
version = "0.14"
features = ["serde-serialize"]
